apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.name" . }} 
  namespace: {{ default .Release.Namespace .Values.mysql.namespace }}
data:
  mysql_database: {{ .Values.auth.database }}
