apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.name" . }}  
  namespace: {{ default .Release.Namespace .Values.mysql.namespace }}
spec:
  selector:
    app: {{ include "mysql.name" . }}  
  ports:
    - protocol: {{ .Values.mysql.ports.protocol}}
      port: {{ .Values.mysql.ports.port}}  
      targetPort: {{ .Values.mysql.ports.targetPort}}  