apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mysql.name" . }} 
  namespace: {{ default .Release.Namespace .Values.mysql.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi