{{- $rootPassword := include "common.secrets.passwords.manage" (dict "secret" (include "mysql.secretName" .) "key" "mysql-root-password" "length" 10 "providedValues" (list "auth.rootPassword") "honorProvidedValues" true "context" $) | trimAll "\"" | b64dec }}

apiVersion: v1
data:
  mysql-root-password: {{ print $rootPassword | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "mysql.name" . }} 
  namespace: {{ default .Release.Namespace .Values.mysql.namespace }}
type: Opaque