apiVersion: {{ include "apiversion.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "mysql.name" . }}
  namespace: {{ default .Release.Namespace .Values.mysql.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "mysql.name" . }} 
  serviceName: {{ include "mysql.name" . | quote }}
  replicas: {{ .Values.mysql.replicaCount }}
  minReadySeconds: {{ .Values.mysql.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ include "mysql.name" . }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.mysql.terminationGracePeriodSeconds }}
      containers:
      - name: mysql
        image: {{ include "mysql.image" . }}
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ include "mysql.name" . }} 
              key: mysql_database
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mysql.name" . }} 
              key: mysql-root-password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name:  todo-mysql-data
      volumes:
      - name:  todo-mysql-data
        persistentVolumeClaim:
          claimName: {{ include "mysql.name" . }} 