{{- if .Values.ingress.enabled }}
apiVersion: {{ include "apiversion.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "docker.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  {{- if and .Values.ingress.ingressClassName (eq "true" (include "apiversion.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
  {{- if .Values.ingress.hostname }}
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      {{- if .Values.ingress.extraPaths }}
      {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
      {{- end }}
      - path:  {{ .Values.ingress.path }}
        {{- if eq "true" (include "apiversion.ingress.supportsPathType" .) }}
        pathType: {{ .Values.ingress.pathType }}
        {{- end }}
        backend: {{- include "apiversion.ingress.backend" (dict "serviceName" (include "docker.name" .) "servicePort" 3000 "context" $)  | nindent 14 }}
  {{- end }}            
{{- end }}
