{{- $password := include "common.secrets.passwords.manage" (dict "secret" (include "mysql.secretName" .) "key" "mysql-password" "length" 10 "providedValues" (list "auth.password") "honorProvidedValues" true "context" $) | trimAll "\"" | b64dec }}
apiVersion: v1
data:
  mysql-password: {{ print $password | b64enc | quote }}
  mysql_user: {{ .Values.auth.username | default "root" | b64enc | quote }}
kind: Secret
metadata:
  name: {{ include "docker.name" . }}
  namespace: {{ default .Release.Namespace .Values.docker.namespace }}
type: Opaque
