apiVersion: v1
kind: Service
metadata:
  annotations:
  name: {{ include "docker.name" . }} 
  namespace: {{ default .Release.Namespace .Values.docker.namespace }}
spec:
  ports:
  - port: {{ .Values.docker.ports.port }} 
    {{- if eq .Values.service.type "LoadBalancer"  -}}
    nodePort: {{ .Values.docker.ports.nodePort }}
    {{- end }}
    protocol: {{ .Values.docker.ports.protocol }}
    targetPort: {{ .Values.docker.ports.targetPort }}
  selector:
    run: {{ include "docker.name" . }} 
  sessionAffinity: None
  type: {{ .Values.service.type }}

