apiVersion: {{ include "apiversion.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "docker.name" . }} 
  namespace: {{ default .Release.Namespace .Values.docker.namespace }}
spec:
  selector:
    matchLabels:
      run: {{ include "docker.name" . }} 
  replicas: {{ .Values.docker.replicaCount }}
  template:
    metadata:
      labels:
        run: {{ include "docker.name" . }} 
    spec:
      containers:
      - name: my-app
        image: {{ include "docker.image" . }}
        ports:
        - containerPort: {{ .Values.docker.ports.targetPort }}
        env:
            - name: MYSQL_HOST
              value: {{ include "mysql.name" . }}.{{ default .Release.Namespace .Values.mysql.namespace }}.svc.cluster.local
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "docker.name" . }}
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "docker.name" . }}
                  key: mysql-password
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "docker.name" . }}
                  key: mysql_database
      imagePullSecrets:
      - name: my-dockerhub-secret
      initContainers:
      - name: wait-services
        image: busybox:latest
        command: ["/bin/sh"]
        args:
         - -c
         - >-
             until nc -vz {{ include "mysql.name" . }}.{{ default .Release.Namespace .Values.mysql.namespace }}.svc.cluster.local 3306; do echo "wait mysql"; sleep 1; done;
