apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker.name" . }}
  namespace: {{ default .Release.Namespace .Values.docker.namespace }}
data:
  mysql_database: {{ .Values.auth.database }}